name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: gcr.io/mipro-traingraph/mipro-traingraph:latest
    - name: Deploy to Google Cloud Run
      run: |
        echo -e "${{ secrets.GCR_JSON_KEY }}" > gcloud_key.json
        gcloud auth activate-service-account --key-file gcloud_key.json
        gcloud config set run/platform managed
        gcloud config set run/region europe-north1
        gcloud run deploy mipro-traingraph \
          --image gcr.io/mipro-traingraph/mipro-traingraph:latest \
          --allow-unauthenticated \
          --set-env-vars SPRING_PROFILES_ACTIVE=gcp